# Author:    Evan K. Irving-Pease
# Copyright: Copyright 2021, University of Copenhagen
# Email:     evan.irvingpease@gmail.com
# License:   MIT

# default reference panel
refpanel: refpanel-v1

# data sources, containing samples and individual library accessions
source:

  1000g:
    # 1000 Genomes Project (1000G)
    # Byrska-Bishop et al. (2021) `bioRxiv` (n=3202)
    # https://doi.org/10.1101/2021.02.06.430068
    samples: data/source/1000g/1000g-samples.tsv
    pedigree: data/source/1000g/1000g-trios.ped

  hgdp:
    # Human Genome Diversity Project (HGDP)
    # Bergström et al. (2020) `Science` (n=816)
    # https://doi.org/10.1126/science.aay5012
    samples: data/source/hgdp/hgdp-samples.tsv
    prephased: data/source/hgdp/hgdp-10x-gVCFs.tsv

  sgdp:
    # Simons Genome Diversity Project (SGDP)
    # Mallick et al. (2016) `Nature` (n=252)
    # https://doi.org/10.1038/nature18964
    samples: data/source/sgdp/sgdp-samples.tsv

  ggvp:
    # Gambian Genome Variation Project (GGVP)
    # Band et al. (2019) `Nature Communications` (n=400)
    # https://doi.org/10.1038/s41467-019-13480-z
    samples: data/source/ggvp/ggvp-samples.tsv
    accessions: data/source/ggvp/ggvp-accessions.tsv
    pedigree: data/source/ggvp/ggvp-trios.ped
    ena_ftp: true

  appg:
    # Arabian Peninsula Population Genomic (APPG) study
    # Almarri et al. (2021) `Cell` (n=137)
    # https://doi.org/10.1016/j.cell.2021.07.013
    samples: data/source/appg/appg-samples.tsv
    accessions: data/source/appg/appg-accessions.tsv
    prephased: data/source/appg/appg-10x-gVCFs.tsv
    ena_ftp: true

  PRJNA76713:
    # Meyer et al. (2012) `Science` (n=8)
    # https://doi.org/10.1126/science.1224344
    samples: data/source/PRJNA76713/PRJNA76713-samples.tsv

  PRJEB16019:
    # Mondal et al. (2016) `Nature Genetics` (n=60)
    # https://doi.org/10.1038/ng.3621
    samples: data/source/PRJEB16019/PRJEB16019-samples.tsv
    accessions: data/source/PRJEB16019/PRJEB16019-accessions.tsv
    ena_ftp: true

  PRJEB26721:
    # McColl et al. (2018) `Science` (n=2)
    # https://doi.org/10.1126/science.aat3628
    samples: data/source/PRJEB26721/PRJEB26721-samples.tsv
    accessions: data/source/PRJEB26721/PRJEB26721-accessions.tsv
    ena_ftp: true

  PRJEB26599:
    # Gelabert et al. (2019) `BMC Genomics` (n=12)
    # https://doi.org/10.1186/s12864-019-5529-0
    samples: data/source/PRJEB26599/PRJEB26599-samples.tsv
    accessions: data/source/PRJEB26599/PRJEB26599-accessions.tsv
    ena_ftp: true

  PRJEB29142:
    # Serra-Vidal et al. (2019) `Current Biology` (n=21)
    # https://doi.org/10.1016/j.cub.2019.09.050
    samples: data/source/PRJEB29142/PRJEB29142-samples.tsv
    accessions: data/source/PRJEB29142/PRJEB29142-accessions.tsv
    ena_ftp: true

  PRJEB28198:
    # Lorente-Galdos et al. (2019) `Genome Biology` (n=9
    # https://doi.org/10.1186/s13059-019-1684-5
    samples: data/source/PRJEB28198/PRJEB28198-samples.tsv
    accessions: data/source/PRJEB28198/PRJEB28198-accessions.tsv
    ena_ftp: true

  PRJNA660888:
    # Crooks et al. (2020) `BMC Genetics` (n=3)
    # https://doi.org/10.1186/s12863-020-00917-4
    samples: data/source/PRJNA660888/PRJNA660888-samples.tsv
    accessions: data/source/PRJNA660888/PRJNA660888-accessions.tsv
    ena_ftp: true

  cgg-afr:
    # Unpublished African genomes from the CGG (n=48)
    samples: data/source/cgg-afr/cgg-afr-samples.tsv
    accessions: data/source/cgg-afr/cgg-afr-accessions.tsv
    private: true


# reference panels, aggregations of samples across data sources
panel:

  1000g:
    # reference panel of the 1000G samples
    samples: data/source/1000g/1000g-panel.tsv
    pedigree: data/panel/refpanel-v1/refpanel-v1.ped

  refpanel-v1:
    # reference panel of all the public data sources (n=4,926)
    samples: data/panel/refpanel-v1/refpanel-v1.tsv
    pedigree: data/panel/refpanel-v1/refpanel-v1.ped

  cgg-afr-v1:
    # reference panel of the CGG-AFR samples + all the public samples in refpanel-v1 (n=4,974)
    samples: data/source/cgg-afr/cgg-afr-panel.tsv
    pedigree: data/panel/refpanel-v1/refpanel-v1.ped


# mapping of readgroup tags to accession metadata column names
readgroup:
  ID: accession
  SM: sample
  CN: center
  PL: platform
  LB: library
  DS: description

# list of chromosomes in GRCh38
chroms: [ chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY, chrM, others ]
