# Author:    Evan K. Irving-Pease
# Copyright: Copyright 2021, University of Copenhagen
# Email:     evan.irvingpease@gmail.com
# License:   MIT

# default reference panel
refpanel: test

# data sources, containing samples and individual library accessions
source:

  1000g:
    # 1000 Genomes Project (TGP) (n=3202; inc. 2504 unrelated + 698 related)
    # https://doi.org/10.1101/2021.02.06.430068
    samples: data/source/1000g/1000g-samples.tsv

  hgdp:
    # Human Genome Diversity Project (HGDP) (n=929; including 111 samples from SGDP)
    # https://doi.org/10.1126/science.aay5012
    samples: data/source/hgdp/hgdp-samples.tsv

  sgdp:
    # Simons Genome Diversity Project (SGDP) (n=231; excluding overlap from 1000G and HGDP)
    # https://doi.org/10.1038/nature18964
    samples: data/source/sgdp/sgdp-samples.tsv

  ggvp:
    # Gambian Genome Variation Project (GGVP) (n=394; excluding 118 from 1000G, and 6 missing from IGSR)
    # missing: SC_GMFUL5306403, SC_GMFUL5306370, SC_GMMAN5482315, SC_GMFUL5306362, SC_GMFUL5306428, SC_GMFUL5306378
    # https://doi.org/10.1038/s41467-019-13480-z
    samples: data/source/ggvp/ggvp-panel.tsv

  appg:
    # Arabian Peninsula Population Genomic (APPG) study (n=137)
    # https://doi.org/10.1016/j.cell.2021.07.013
    samples: data/source/appg/appg-panel.tsv
    accessions: data/source/appg/appg-accessions.tsv
    ena_ftp: true

  PRJEB26721:
    # Jehai genomes from West Malaysia (n=2)
    # https://doi.org/10.1126/science.aat3628
    samples: data/source/PRJEB26721/PRJEB26721-samples.tsv
    accessions: data/source/PRJEB26721/PRJEB26721-accessions.tsv
    ena_ftp: true

  PRJEB28198:
    # Pan-African genomes (n=9)
    # https://doi.org/10.1186/s13059-019-1684-5
    samples: data/source/PRJEB28198/PRJEB28198-samples.tsv
    accessions: data/source/PRJEB28198/PRJEB28198-accessions.tsv
    ena_ftp: true

  PRJNA46161:
    # Khoisan and Bantu genomes from southern Africa (n=3)
    # https://doi.org/10.1038/nature08795
    samples: data/source/PRJNA46161/PRJNA46161-samples.tsv
    accessions: data/source/PRJNA46161/PRJNA46161-accessions.tsv
    ena_ftp: true

  cgg-afr:
    # Unpublished African genomes from the CGG (n=48)
    samples: data/source/cgg-afr/cgg-afr-panel.tsv
    accessions: data/source/cgg-afr/cgg-afr-accessions.tsv
    public: false


# reference panels, aggregations of samples across data sources
panel:

  1000g:
    # reference panel of the 1000G samples
    samples: data/source/1000g/1000g-panel.tsv
    pedigree: data/source/1000g/1000g-trios.ped

  refpanel-v1:
    # reference panel of all the public data sources (n=4,893)
    samples: data/panel/refpanel-v1/refpanel-v1-panel.tsv
    pedigree: data/source/1000g/1000g-trios.ped

  cgg-afr:
    # reference panel of the CGG-AFR samples
    samples: data/source/cgg-afr/cgg-afr-panel.tsv


# mapping of readgroup tags to accession metadata column names
readgroup:
  ID: accession
  SM: sample
  CN: center
  PL: platform
  LB: library
  DS: description

# list of chromosomes in GRCh38
chroms: [ chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY, chrM, others ]
