# Author:    Evan K. Irving-Pease
# Copyright: Copyright 2021, University of Copenhagen
# Email:     evan.irvingpease@gmail.com
# License:   MIT

# default reference panel
refpanel: example-panel

# data sources, containing samples and individual library accessions
source:

  example:
    # metadata sheet containing the list of samples and populations
    samples: example/example-samples.tsv

    # metadata sheet containing the list of accessions and fastq files
    accessions: example/example-accessions.tsv

    # mapping of readgroup tags to accession metadata column names
    readgroup:
      ID: accession
      SM: sample
      CN: center
      PL: platform
      LB: library
      DS: description

# aggregations of different data sources
panel:

  example-panel:
    # metadata sheet containing the list of samples and populations for this reference panel
    samples: example/example-samples.tsv


# list of chromosomes in GRCh38
chroms: [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY, chrM, others]
