channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.3.1
  - bedtools=2.30.0
  - bwa=0.7.15
  - gatk=3.5
  - pandas=1.3.4
  - picard=2.5.0
  - python=3.9.7
  - samtools=1.3.1
  - snakefmt=0.4.4
  - snakemake=6.10.0
  - tabix=1.11
